server:
  port: 8001

mybatis:
  type-aliases-package: com.kuang.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db01?characterEncoding=utf8
    username: root
    password: mysqladmin


#eureka的配置  :服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #可以修改默认的配置信息



#info配置
info:
  app.name: kuang-springcloud
  company.name: blog.kuangstudy.com



